name: CI

on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:

          - name: Code style checks
            os: ubuntu-latest
            python: 3.9
            toxenv: codestyle

          - name: Minimal dependencies
            os: ubuntu-latest
            python: 3.9
            toxenv: py39-test

          # Docs are build directly on readthedocs even for PR.
          # - name: Documentation build
          #   os: ubuntu-latest
          #   python: 3.9
          #   toxenv: build_docs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install system dependencies
      if: startsWith(matrix.toxenv, 'build_docs')
      run: sudo apt-get install graphviz
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: python -m pip install --upgrade tox codecov
    - name: Run tests
      run: tox ${{ matrix.toxargs }} -e ${{ matrix.toxenv }} -- ${{ matrix.toxposargs }}
